name: select_any
description: A flexible library for listing data in lists/tables
version: 0.0.1
repository: https://github.com/ReniDelonzek/select_any

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  intl: ^0.17.0
  data_table_plus: ^0.0.1
  flutter_date_pickers: ^0.2.4
  share_extend: ^1.1.9
  path_provider: ^2.0.1 
  diacritic: ^0.1.1
  bloc_pattern: ^2.5.1
  mobx: ^1.1.0
  flutter_mobx: ^1.1.0+2
  msk_utils: ^0.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.7.3
  mobx_codegen: ^1.1.2
  flutter_test:
    sdk: flutter

# dependency_overrides:
#   meta: "1.7.0"
#   analyzer: "1.7.2"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - images/

scripts:
   build: flutter pub run build_runner build --delete-conflicting-outputs
   watch: flutter pub run build_runner watch --delete-conflicting-outputs
   clean: flutter pub run build_runner clean
    
