name: select_any
description: A flexible library for listing data in lists/tables
version: 0.2.6
repository: https://github.com/ReniDelonzek/select_any

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  intl: ^0.17.0
  data_table_plus: ^0.0.1
  flutter_date_pickers: ^0.4.0
  share_extend: ^2.0.0
  path_provider: ^2.0.2 
  diacritic: ^0.1.3
  bloc_pattern: ^3.0.0
  mobx: ^2.0.4
  flutter_mobx: ^2.0.2
  msk_utils: ">=1.0.5"
  flutter:
    sdk: flutter
  collection: 

dev_dependencies:
  build_runner: ^2.1.1
  mobx_codegen: ^2.0.3
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - images/

scripts:
   build: flutter pub run build_runner build --delete-conflicting-outputs
   watch: flutter pub run build_runner watch --delete-conflicting-outputs
   clean: flutter pub run build_runner clean
    
