name: select_any
description: A flexible library for listing data in lists/tables
version: 0.0.1
author:
homepage:
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  data_table_plus:
    git:
      url: git@github.com:ReniDelonzek/data_table_plus.git
      ref: 64a0d73991c5694697fb4d77f1ab1952eba43e34
    #path: "C:/Users/reni/Downloads/Projetos/flutter/libs/data_table_2"
  flutter_date_pickers: ^0.2.4
  share_extend: ^1.1.9
  path_provider: ^2.0.1 
  diacritic: ^0.1.1
  bloc_pattern: ^2.5.1
  mobx: ^0.3.9+3
  msk_utils:
    #path: "C:/Users/reni/Downloads/Projetos/agro/libs/msk_utils"
    #path: /Users/reni/Downloads/Projetos/MSK/flutter/msk_plugin/msk_utils
    git:
      url: git@github.com:ReniDelonzek/msk_utils.git
      ref: f9a8202a02fc8249614e61964785323acc6586df
  flutter:
    sdk: flutter

dependency_overrides:
  intl: ^0.16.1

dev_dependencies:
  build_runner: ^1.7.3
  mobx_codegen: ^0.3.10+1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - images/

scripts:
   build: flutter pub run build_runner build --delete-conflicting-outputs
   watch: flutter pub run build_runner watch --delete-conflicting-outputs
   clean: flutter pub run build_runner clean
    
