name: select_any
description: A flexible library for listing data in lists/tables
version: 1.1.1
repository: https://github.com/ReniDelonzek/select_any

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  intl: ^0.19.0
  data_table_plus: ^0.0.2
  flutter_date_pickers: ^0.4.2 
  share_extend_plus: ^0.0.1
  path_provider: ^2.0.15
  diacritic: ^0.1.3
  bloc_pattern: ^3.0.1
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  msk_utils: ">=2.0.0"
  flutter:
    sdk: flutter
  collection:

dev_dependencies:
  build_runner: ^2.4.5
  mobx_codegen: ^2.3.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: ^0.19.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - images/

scripts:
  build: flutter pub run build_runner build --delete-conflicting-outputs
  watch: flutter pub run build_runner watch --delete-conflicting-outputs
  clean: flutter pub run build_runner clean
